### ISSUE TITLE
build broken if used with latest version of go-github library

### ISSUE THREAD

**Issue by dape-wg2** [cloudposse/github-status-updater#7]
There was a breaking API change in version v16.0.0 of github.com/google/go-github; this cause a compile error here:

https://github.com/cloudposse/github-status-updater/blob/master/main.go#L174

this is caused by the the being changed from ```[]string``` to ```*[]string``` here

https://github.com/google/go-github/blob/v16.0.0/github/repos.go#L639

**Comment by aknysh** [comment]
@dape-wg2  thank you for reporting the issue!
addressed in https://github.com/cloudposse/github-status-updater/pull/8 
and released in https://github.com/cloudposse/github-status-updater/releases/tag/0.2.0
